os: linux
arch:
 - amd64
 - ppc64le
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  ###- "5.8.8"          # fails due to Number::Format depedancy
  #- "dev"              # installs latest developer release of perl (e.g. 5.21.8)
  #- "blead"            # builds perl from git

sudo: false             # faster builds as long as you don't need sudo access

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto

matrix:
  allow_failures:
    - perl: blead       # ignore failures for blead perl
    - perl: 5.12        # not available for ppc64le
      arch: ppc64le
    - perl: 5.10        # not available for ppc64le
      arch: ppc64le
  include:
    - perl: "5.20"
      env: COVERAGE=1   # enables coverage+coveralls reporting
    #powerjobs  
    - perl: "5.20"
      arch: ppc64le
      env: COVERAGE=1   # enables coverage+coveralls reporting

# end
